### ISSUE TITLE
AngularJs tests not working anymore since puppeteer 1.16.0

### ISSUE THREAD

**Issue by ghost** [trion-development/docker-ng-cli-karma#6] opened 2019-07-12 09:54 UTC
First of all, thanks a lot for providing the very useful docker-ng* images!

I'm experiencing problems running AngularJs unit tests with trion/ng-cli-karma in Docker. If I run the same tests from the same directory without docker, the tests are running fine. I noticed this behaviour when I upgraded from puppeteer 1.15.0 to 1.18.1. After I encountered this problem, I tested with the puppeteer versions in between as well, keeping all other conditions/dependencies stable:

Puppeteer 
1.15.0: Tests work fine
1.16.0: After the tests are compiled, a timeout is reported
1.17.0: After the tests are compiled, a ping timeout is reported
1.18.0: After the tests are compiled, a ping timeout is reported
1.18.1: After the tests are compiled, the error below is shown. Different runs report different files. This files are there

Error with 1.18.1: ```
Launching browsers ChromiumHeadlessNoSandbox with concurrency 10
INFO [launcher]: Starting browser ChromiumHeadless
INFO [HeadlessChrome 77.0.3835 (Linux 0.0.0)]: Connected on socket e4CktzR-PL1YNFFYAAAA with id 61911099
HeadlessChrome 77.0.3835 (Linux 0.0.0) ERROR
  An error was thrown in afterAll
  Error: Can't find ./some-file.ts] (required by other-file.ts)
      at require (node_modules/karma-typescript/dist/client/commonjs.js:13:23)
      at node_modules/karma-typescript/dist/client/commonjs.js:18:24
      at Object.global.wrappers./app/other-file.ts.angular (other-file.ts:17 <- otherfile.js:9:1380)
      at require (node_modules/karma-typescript/dist/client/commonjs.js:17:25)
      at node_modules/karma-typescript/dist/client/commonjs.js:18:24
      at Object.global.wrappers./app/yet-another-file.ts.angular (yet-another-file.ts:7 <- yet-another-file.js:9:650)
      at require (node_modules/karma-typescript/dist/client/commonjs.js:17:25)
      at node_modules/karma-typescript/dist/client/commonjs.js:38:9
      at Array.forEach (<anonymous>)
      at node_modules/karma-typescript/dist/client/commonjs.js:37:40
HeadlessChrome 77.0.3835 (Linux 0.0.0): Executed 0 of 0 ERROR (0 secs / 0 secs)```

I'm starting the tests with `sudo docker run --user $(id -u):$(id -g) --rm -v "$PWD":/app trion/ng-cli-karma:8.1.0 yarn karma start ./test/karma.conf.js`

Without docker, I just invoke `yarn karma start ./test/karma.conf.js` from the same directory.

Some more information about the environment: These tests are legacy tests from an AngularJs/Angular-hybrid app that live together with pure Angular apps in a nrwl nx monorepo setup. The pure Angular apps are using the standard Angular cli setup and they work fine with the same docker image.

Any idea, how to solve this?

**Comment by codecoster** [comment] 2019-07-12 12:10
Thanks for your Issue-Report!
Unfortunately, I could not reproduce your issue with a simple karma/puppeteer-setup, using the ng-cli-karma image and puppeteer in Version 1.18.1. 
How is he build-process setup for the tests?
Could you maybe even provide a minimal setup to reproduce your issue?

**Comment by ghost** [comment] 2019-07-12 12:13
Thank you for trying to reproduce the issue. Is was hoping that my description was giving you an idea, what could fail. I will try to assemble a setup that I can share.

**Comment by everflux** [comment] 2019-07-16 15:05
Can you provide the karma configuration?
Does the problem occur with older versions of the image or is this related to the 8.1.0/8.1.1?

**Comment by ghost** [comment] 2019-07-16 15:13
Sorry for not replying earlier! I was not able to reproduce this in a simple scenario so far. 
Having dependencies/yarn.lock, tsconfigs, karma.config etc. all the same with my real project (which I can not share), the problem does not occur. I could only reproduce it so far when copying a lot of the real project files into the project I use to reproduce the issue. I did not yet have time to strip this down to the bare minimum. I hope to have time for this in the next days.

The issue appears with trion/ng-cli-karma:8.0.3 as well.

**Comment by everflux** [comment] 2019-07-16 15:38
Are you resolving the npm dependencies as part of your build or are you using externally resolved dependencies from outside?
Is there a reason that you are using `sudo` to invoke docker, this should not be necessary.

Can you at least share the project build configuration? (We can arrange a private exchange as well to avoid making your project public, if that is any help - you can reach me by mail via tk at trion de)

**Comment by ghost** [comment] 2019-07-17 07:27
Hallo Thomas,

(ich nehme an, Du sprichst deutsch :-) ),

mein Test-Repo ist 
https://github.com/JochenDiekenbrock/debug-angularjs-test
Der Stand da entspricht bis auf den tatsächlichen Programmcode dem, in 
dem das Problem auftritt. Wie bereits geschrieben, hoffe ich kurzfristig 
Zeit zu finden, das Problem weiter einzukreisen. Es scheint ein fieses 
Zusammenspiel mit dem Programmcode zu geben.

Die yarn.lock ist ebenfalls im git, vor dem Build/test läuft jeweils ein 
'yarn install'

sudo weil ich mir nicht die Mühe gemacht habe, meinen User richtig zu 
konfigurieren. Im Jenkins wird aber ohne sudo gestartet, über eine 
Jenkins deklararive Pipeline:
agent {
     docker {
         image "${env.TRION_NG_KARMA}"
         label 'jenkins-agent'
         args '-v $PWD:/app'
     }
}

Viele Grüße aus Hannover, Jochen

Am 16.07.2019 17:38, schrieb Thomas:

**Comment by everflux** [comment] 2019-07-17 07:47
Thanks for the additional information. (German is indeed my native language but to facilitate participation I try to use English as much as possible on public projects.)
Since your local build is working but the Jenkins build breaks, can you provide the pipeline steps?

Does your linked test repository expose the problem? A local build using these steps worked for me

```
docker run --rm -u $(id -u):$(id -g) --rm -v $PWD:/app trion/ng-cli-karma:8.1.0 yarn install
docker run --rm -u $(id -u):$(id -g) --rm -v $PWD:/app trion/ng-cli-karma:8.1.0 yarn karma start ./test/karma.conf.js
```

**Comment by ghost** [comment] 2019-07-17 07:59
sorry, I thought I was replying to a private email...

I fear I was not clear. The linked test repo works, I provided it for the build configuration. It breaks (locally as well as on Jenkins), when I add our program code, which I can not share publicly. I will try to further reduce the necessary code until I can produce a publicly shareable example.

Thank you for your support!

**Comment by ghost** [comment] 2019-07-20 15:12
I spent a lot of time in the meantime to reproduce the problem with a minimum set of files. I was not very successful so far, unfortunately. I tested with ng-cli-karma:8.1.2 as well and it behaved same.

Some findings:
- The chance of getting the error increases with the number of files that are loaded by karma. With only a few files, the error never occurs, with our full project, the error always occurs. With a medium number of files (around 100 files), sometimes the error occurs and sometimes not, without making any changes at all to anything in the project.
- If the error occurs, I can see one or more errors in the Chrome console: `Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES` for files that are included from AngularJS components via templateUrl

I think this problem is not related to ng-cli-karma and it's probably best to just close the issue.
Thank you for listening and for the ng-cli images!

**Comment by everflux** [comment] 2019-07-20 15:20
Can you try if running docker with the following additional flag helps: (assuming you have a sufficient amount of ram on the node)

```
--shm-size 1G
```

It could be related to chrome and the default shared memory size that is allowed by docker containers.

**Comment by ghost** [comment] 2019-07-20 15:51
Thomas, you are a hero! That solves the problem! Thank you very much!

**Comment by everflux** [comment] 2019-07-21 17:35
Wonderful, glad I could help.
I will close this issue then. (Feel free to create a pull request for the README, if you like. I assume this image is used in many contexts like puppeteer or cypress and others might experience a similar issue.)

**Closed as completed by everflux** 2019-07-21 17:35 UTC
